print('================================================================')
print('Faça um programa que receba algo e mostre os seu tipo \n'
'primitivo \n e todas as infoemcaoes possíveis sobre ele.')
valor = input('Digite um valor a sua escolha:')
print('O tipo primitivo é:', type(valor))
print('É um número?', valor.isnumeric())
print('É um uma letra?', valor.isalpha())
print('Tem espaço ?', valor.isspace())
print('É um alfanúmerico?', valor.isalnum())
print('Está em minúscula ?', valor.islower())
print('Éstá em maiúscula ?', valor.istitle())
print('É um númerico?', valor.isupper())
print('================================================================')
print()
