print('===========================================================')
print('Crie um programa  que receb um número e faça a sua tabuada? ')
n = int(input('Digite o seu número:'))
print('O seu número é:', n)
print(n,'x1=',n*1)
print(n,'x2=',n*2)
print(n,'x3=',n*3)
print(n,'x4=',n*4)
print(n,'x5=',n*5)
print(n,'x6=',n*6)
print(n,'x7=',n*7)
print(n,'x8=',n*8)
print(n,'x9=',n*9)
print(n,'x10=',n*10)
print('===========================================================')
