print()
print('{:=^80}'.format(' Exercício Python 75 '))
print('Desenvolva um programa que leia quatro valores pelo teclado e guarde-os em uma tupla.')
print('No final, mostre:')
print('A) Quantas vezes apareceu o valor 9.')
print('B) Em que posição foi digitado o primeiro valor 3.')
print('C) Quais foram os números pares.')
print()
