print('')
print('{:=^80}'.format(' Exercício Python 79 '))
print('')
print('Crie um programa onde o usuário possa digitar vários valores numéricos e cadastre-os em uma lista.')
print('Caso o número já exista lá dentro, ele não será adicionado.')
print('No final, serão exibidos todos os valores únicos digitados, em ordem crescente')
print('')